name: xcollection-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cf_xarray
  - jupyterlab
  - myst-nb
  - netcdf4
  - pip
  - pooch
  - pydantic
  - furo
  - sphinx-copybutton
  - xarray
  - zarr
  - pip:
      - sphinxext-opengraph
      - sphinx-comments
      - -r ../requirements.txt
      - -e ..
